[package]
name = "vale_bridge"
version = "0.1.0"
edition = "2021"

[features]
default = ["plugins", "events"]
plugins = []
events = []

[dependencies]
chrono = "0.4.19"
serde = "1.0"
rhai = { version = "1.3.0", features = ["sync"] }

